use_frameworks!

platform :ios, '8.0'

target 'MDReactPageKit_Example' do
  pod 'MDReactPageKit', :path => '../'

  target 'MDReactPageKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
