
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'
source 'https://github.com/Leon0206/MDSpecs.git'

platform :ios, '10.0'

target 'ReactivePageKit_Example' do
  pod 'ReactivePageKit', :path => '../'

end
